### PR TITLE
Default port.name to "Port N"

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by dotdoom** [comment]
Tested via:

```shell
$ ./setup.sh
$ source venv/bin/activate
(venv) $ python3 -m pytest

...

Required test coverage of 95.0% reached. Total coverage: 96.94%
============================================ 159 passed, 1 warning in 2.09s ============================================
```

**Comment by Kane610** [comment]
Thanks. Ill have a look next week once Im back home

**Comment by dotdoom** [comment]
Friendly ping @Kane610, hope you got home safe.

**Review by Kane610 — CHANGES_REQUESTED** [review]
Sorry, have been really busy IRL

**Comment by dotdoom** [comment]
Merged the change; I am not sure if Port could be None, this was a case of defensive programming.  I have removed that branch now.

**Comment by Kane610** [comment]
Almost there, you need to run ruff

**Comment by dotdoom** [comment]
That is now done!

**Review by Kane610 — APPROVED** [review]
Allright!

**Pull request merged**
