### PR TITLE
Add device temperature

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Review by Kane610 — APPROVED** [review]
Sweet 🎉

**Comment by Gatsby-Lee** [comment]
When are you planning to apply this change to HA UniFi integration?

**Comment by kimdv** [comment]
> When are you planning to apply this change to HA UniFi integration?

Hi @Gatsby-Lee, 
When this is merged: https://github.com/home-assistant/core/pull/116737 I will start working on it :)
I have some draft on my computer already. :)

**Comment by Gatsby-Lee** [comment]
> > When are you planning to apply this change to HA UniFi integration?
> 
> Hi @Gatsby-Lee, When this is merged: [home-assistant/core#116737](https://github.com/home-assistant/core/pull/116737) I will start working on it :) I have some draft on my computer already. :)




> > When are you planning to apply this change to HA UniFi integration?
> 
> Hi @Gatsby-Lee, When this is merged: [home-assistant/core#116737](https://github.com/home-assistant/core/pull/116737) I will start working on it :) I have some draft on my computer already. :)

@kimdv
Thank you!!

**Comment by Gatsby-Lee** [comment]
@kimdv hello,
I noticed that the https://github.com/home-assistant/core/pull/116737 has been merged.
Have you started working on the temperature-related integration? 

Thank you

**Comment by Gatsby-Lee** [comment]
ah, maybe this is the one you're working on.
Plz correct me if I am wrong.
https://github.com/home-assistant/core/pull/122518

**Pull request merged**
