### PR TITLE
Retry login when session expires

### PR DESCRIPTION
**Pull request by bdraco**
Verified replication and fix for https://github.com/home-assistant/core/issues/33024

If we need tests I probably need to bring in `aioresponses` to mock specific urls

### CODE REVIEW

**Comment by Kane610** [comment]
This looks great @bdraco , please add a testing as well

**Comment by tnowakow** [comment]
Hi guys, been tracking this since it started popping up.  I don't know how github works that much but wondering if this has been committed yet and/or when we could see it incorporated into the main integration in HA.  Thank you!

**Comment by bdraco** [comment]
Its not done yet.  I should have time before 0.113 ships to get this solved

**Comment by Kane610** [comment]
@bdraco i could merge this now to get it out into a service release and you can add the test later if you prefer

**Comment by bdraco** [comment]
@Kane610 Tests added. Good thing I did as I forget to throw if we had already retried login once.

**Comment by Kane610** [comment]
Thanks! I'll have a look tomorrow and get it merged. Do you have a PR ready in hass?

**Comment by bdraco** [comment]
> Thanks! I'll have a look tomorrow and get it merged. Do you have a PR ready in hass? Or should I bump it?

Please bump it!

**Comment by tnowakow** [comment]
You guys are amazing, thank you very much

**Pull request merged**
