### PR TITLE
Add some additional properties to `Device`

### PR DESCRIPTION
**Pull request by joshuaspence**
Supporting change for home-assistant/core#74025.

### CODE REVIEW

**Review by Kane610 — COMMENTED** [review]
Could we create two data classes for temperatures and system-stats and handle them similar to ports and outlets (only simpler)

**Comment by Kane610** [comment]
Any plans to continue this @joshuaspence ?

**Comment by joshuaspence** [comment]
Sorry, life got in the way

**Comment by Kane610** [comment]
> Sorry, life got in the way

It happens! Thanks for replying.

**Pull request closed without merging**
